name: Tests

on: [push]

env:
  IMAGE_NAME: coap
  IMAGE_TAGGED: coap:${{ github.sha }}

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Build server
        working-directory: server
        run: go build

      - name: Build client
        working-directory: client
        run: go build

      - name: Build image
        run: |
          docker build -t ${{ env.IMAGE_TAGGED }} .

      - name: Log in to the infrastructure container registry
        run: |
          docker login -u ${{ vars.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ vars.REGISTRY_LOGIN_SERVER }}

      - name: Push image to the infrastructure container registry
        run: |
          docker tag ${{ env.IMAGE_TAGGED }} ${{vars.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_TAGGED }}
          docker push ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_TAGGED }}

  tests:
    needs: [image]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        networking:
          - ipv4
          - ipv6

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Build client
        working-directory: client
        run: go build

      - name: Log in to infrastructure container registry
        run: |
          docker login -u ${{ vars.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ vars.REGISTRY_LOGIN_SERVER }}

      - name: Pull image from the infrastructure container registry
        run: |
          docker pull ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_TAGGED }}

      - name: Run image (IPv4)
        if: matrix.networking == 'ipv4'
        env:
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
          STORAGE_CONTAINER_NAME: ${{ vars.STORAGE_CONTAINER_NAME }}
        run: |
          docker run --network=host --sysctl net.ipv6.conf.all.disable_ipv6=0 --sysctl net.ipv4.conf.all.disable_ipv4=1 -p 5688:5688/udp -p 5689:5689/udp -e STORAGE_CONNECTION_STRING -e STORAGE_CONTAINER_NAME -d ${{ env.IMAGE_TAGGED }}

      - name: Run image (IPv6)
        if: matrix.networking == 'ipv6'
        env:
          STORAGE_CONNECTION_STRING: ${{ secrets.STORAGE_CONNECTION_STRING }}
          STORAGE_CONTAINER_NAME: ${{ vars.STORAGE_CONTAINER_NAME }}
        run: |
          docker run --network=host --sysctl net.ipv6.conf.all.disable_ipv6=1 --sysctl net.ipv4.conf.all.disable_ipv4=0 -p 5688:5688/udp -p 5689:5689/udp -e STORAGE_CONNECTION_STRING -e STORAGE_CONTAINER_NAME -d ${{ env.IMAGE_TAGGED }}

      - run: docker ps

      - name: Run test client (IPv4)
        if: matrix.networking == 'ipv4'
        working-directory: client
        run: go run client.go -address 127.0.0.1

      - name: Run test client (IPv6)
        if: matrix.networking == 'ipv6'
        working-directory: client
        run: go run client.go -address ::1 -udp6

      - name: Docker logs
        if: always()
        run: |
          docker ps
          docker container logs `docker ps | grep ${{ env.IMAGE_TAGGED }} | awk '{ print $1; }'`

  publish:
    if: github.ref == 'refs/heads/saga'

    needs: [tests]

    runs-on: ubuntu-latest

    steps:
      - name: Log in to infrastructure container registry
        run: |
          docker login -u ${{ vars.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ vars.REGISTRY_LOGIN_SERVER }}

      - name: Pull image from the infrastructure container registry
        run: |
          docker pull ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_TAGGED }}

      - name: Push image to the infrastructure container registry as latest
        run: |
          docker tag ${{ env.IMAGE_TAGGED }} ${{vars.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_NAME }}:latest
          docker push ${{vars.REGISTRY_LOGIN_SERVER}}/${{ env.IMAGE_NAME }}:latest
