name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6

      - name: Prepare self-signed cert
        run: |
          mkdir certificates
          cd certificates
          # CA key and certificate
          openssl genrsa -out CA.key 2048
          openssl req -new -x509 -nodes -key CA.key -sha256 -days 365 -extensions v3_ca -out CA.crt -subj '/OU=Nordic Developer Academy'
          # Server key
          openssl genrsa -out server.key 2048
          # CSR
          openssl req -out server.csr -key server.key -new -subj '/CN=coap.academy.nordicsemi.com'
          # Sign CSR
          openssl x509 -req -in server.csr -CA CA.crt -CAkey CA.key -CAcreateserial -out server.crt -days 365

      - name: Build server
        working-directory: server
        run: go build

      - name: Build client
        working-directory: client
        run: go build

      - name: Build image
        run: |
          docker build -t academy-coap .

      - name: Run image
        run: docker run -p 5688:5688/udp -d academy-coap

      - name: Run test client
        working-directory: client
        run: go run main.go
