name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6

      - name: Build
        working-directory: server
        run: go build

      - name: Build
        working-directory: client
        run: go build

      - name: Build image
        run: |
          docker build -t academy-coap .

      - name: Run image
        run: docker run -p 5688:5688/udp -d academy-coap

      - name: Run test client
        working-directory: client
        run: go run main.go
